import { fingerprint } from '../lib/contract.js';
const e = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const json = value => JSON.stringify(value).replaceAll('<','\\u003c');
const n = value => String(value).padStart(2,'0');
const kindNames = {binding:'이름과 객체', flow:'실행 순서', collection:'값의 구성', branch:'조건과 선택', pipeline:'입력에서 결과로', object:'객체의 구조', timeline:'상태의 변화'};
function code(text) {
  return text.split('\n').map((line,i)=>`<span class="code-line" data-code-line="${i+1}"><span class="line-number">${n(i+1)}</span><span class="line-source">${e(line)||' '}</span></span>`).join('');
}
function frame(title, description, body, prefix='') {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · ScrollLand</title><meta name="description" content="${e(description)}"><meta name="theme-color" content="#101815"><link rel="icon" href="${prefix}favicon.svg"><link rel="stylesheet" href="${prefix}styles.css?v=3"><script defer src="${prefix}lib/gsap.min.js"></script><script defer src="${prefix}lib/ScrollTrigger.min.js"></script><script type="module" src="${prefix}app.js?v=3"></script></head><body><a class="skip-link" href="#main">학습 내용으로 건너뛰기</a><header class="site-header"><a class="brand" href="${prefix}index.html"><span class="brand-glyph" aria-hidden="true">↳</span>ScrollLand<span class="brand-dot">.</span></a><span class="header-current" data-header-current>SCROLL TO UNDERSTAND</span><a class="catalog-link" href="${prefix}index.html#courses">전체 목차 ↗</a><div class="global-progress" aria-hidden="true"><i data-global-progress></i></div></header>${body}<footer class="site-footer"><p>한 줄씩, 이해가 움직입니다.</p><span>ScrollLand · Python</span><a href="${prefix}README.md">자료·검증 범위</a></footer></body></html>\n`;
}
function hero() {
 return `<section class="hero" data-hero><div class="hero-sticky"><div class="hero-topline"><span>PYTHON, IN MOTION.</span><span>8 COURSES / 44 LESSONS</span></div><h1 class="hero-title">스크롤하면,<br><span>코드가 보인다.</span></h1><p class="hero-description">한 줄의 코드에서 값이 바뀌는 순간까지.<br>직접 움직이며 이해하는 Python.</p><div class="hero-machine" aria-hidden="true"><div class="hero-code"><span class="code-comment"># a small change</span><p>birds <span>=</span> <b>7</b></p><p>birds <span>=</span> birds <span>+</span> <b>1</b></p></div><svg viewBox="0 0 500 210" class="hero-diagram"><path class="hero-path" d="M112 105 C230 105 235 105 344 105"/><rect x="20" y="78" width="115" height="54" rx="27"/><text x="78" y="110" text-anchor="middle">birds</text><circle class="hero-orbit" cx="377" cy="105" r="82"/><circle class="hero-object" cx="377" cy="105" r="57"/><text class="hero-value" x="377" y="119" text-anchor="middle">7</text><text class="hero-value-next" x="377" y="119" text-anchor="middle">8</text></svg></div><div class="hero-bottom"><p>아래로 스크롤하세요 <span>↓</span></p><span>멈추면, 그 순간을 살펴볼 수 있습니다.</span></div><div class="hero-watermark" aria-hidden="true">Scroll.</div></div></section>`;
}
function sourceInput(section) {
 const input = 'stdin' in section ? `<div><h4>표준 입력</h4><pre>${e(section.stdin || '(빈 입력)')}</pre></div>`:'';
 const files = Object.entries(section.files||{}).map(([name,text])=>`<div><h4>${e(name)}</h4><pre>${e(text||'(빈 파일)')}</pre></div>`).join('');
 return input||files ? `<div class="input-material"><h3>예제에 제공한 입력 자료</h3>${input}${files}</div>`:'';
}
function readableNodes(nodes) {
 return `<dl class="readable-nodes">${nodes.map(node=>`<div><dt>${e(node.label)}</dt><dd>${e(node.value)}</dd></div>`).join('')}</dl>`;
}
function renderScene(section, i, lesson, motion) {
 const id=`${lesson.slug}-scene-${i+1}`;
 return `${sourceInput(section) ? `<aside class="scene-input-deck">${sourceInput(section)}</aside>` : ''}<section class="scene" id="${id}" data-scroll-scene ${Math.max(...section.body.map(x=>x.length))>180?'data-dense="true"':''} data-kind="${section.diagram.type}" style="--beats:${section.trace.length+1}"><div class="scene-stage" hidden aria-hidden="true"><div class="scene-top"><span class="scene-kicker">${n(i+1)} / ${n(lesson.sections.length)} <i></i> ${e(kindNames[section.diagram.type])}</span><span class="scene-position" data-position>01 / ${n(section.trace.length+1)}</span></div><h2 class="scene-heading">${e(section.title)}</h2><div class="learning-stage"><div class="code-pane"><div class="pane-label"><span>PYTHON</span><span class="code-file">${e(lesson.slug)}.py</span></div><pre class="stage-code"><code>${code(section.code)}</code></pre><div class="stage-output"><span>출력</span><samp data-output></samp><i data-output-empty>아직 출력 없음</i></div></div><div class="visual-pane"><span class="pane-label">${e(kindNames[section.diagram.type])}</span><div class="state-canvas" data-state-canvas></div><p class="diagram-state" data-state-caption></p></div></div><div class="narration"><div><span class="step-eyebrow" data-step-label></span><p class="step-state" data-step-state></p></div><p class="step-body" data-step-body></p></div><div class="scene-bottom"><span>스크롤해서 이어 보기</span><div class="scene-progress"><i data-scene-progress></i></div><span>↓</span></div></div><div class="scene-transcript"><p class="eyebrow">장면 ${i+1}</p><h2>${e(section.title)}</h2>${section.body.map(x=>`<p>${e(x)}</p>`).join('')}<h3>Python 코드</h3><pre tabindex="0" aria-label="${e(section.title)} Python 코드"><code>${e(section.code)}</code></pre><h3>실행 결과</h3><pre>${e(section.output||'(표준 출력 없음)')}</pre><h3>${e(kindNames[section.diagram.type])}</h3><p>${e(section.diagram.caption)}</p><ol>${section.trace.map((x,j)=>`<li><strong>${e(x.label)}</strong><p>${e(x.state)}</p>${readableNodes(motion?.steps?.[j]?.nodes || [])}<p>이 단계의 출력: ${e(motion?.steps?.[j]?.output || '(표준 출력 없음)')}</p></li>`).join('')}</ol><h3>결과와 관계 확인</h3>${readableNodes(motion?.finalNodes || section.diagram.nodes)}</div><script type="application/json" data-scene-data>${json({section,motion:motion||null})}</script></section>`;
}
function renderQuiz(lesson) {
 return `<section class="scroll-check" data-scroll-check><div class="check-stage"><p class="eyebrow">잠깐, 머릿속으로 실행해 보세요.</p><h2>${e(lesson.quiz.question)}</h2><p class="check-hint">답을 떠올린 뒤, 조금 더 내려 보세요.</p><div class="answer-reveal" data-answer-reveal><div class="answer-main"><span>정답</span><strong>${e(lesson.quiz.options.find(x=>x.correct).text)}</strong></div>${lesson.quiz.options.map(x=>`<p class="answer-reason"><strong>${x.correct?'정답':'오답'}: ${e(x.text)}</strong><span>${e(x.feedback)}</span></p>`).join('')}</div></div></section>`;
}
function article(lesson, content, prefix='', single=false) {
 const heading=single?'h1':'h2';
 const course=content.curriculum.courses.find(c=>c.id===lesson.courseId), index=content.order.indexOf(lesson.slug);
 const scenes=content.motion?.lessons?.[lesson.slug]||[];
 return `<article class="lesson-article" id="lesson-${lesson.slug}" data-lesson-article data-title="${e(lesson.title)}" data-content-fingerprint="${fingerprint(lesson)}"><header class="lesson-opening"><p class="eyebrow">${n(index+1)} / ${n(content.order.length)} · ${e(course.title)}</p><${heading}>${e(lesson.title)}</${heading}><p class="opening-problem">${e(lesson.problem)}</p><div class="opening-bottom"><p>${e(lesson.goal)}</p><span>SCROLL TO EXPLORE ↓</span></div>${lesson.prerequisites.length?`<p class="prerequisites">먼저 익힐 개념 · ${lesson.prerequisites.map(slug=>`<a href="${prefix}index.html#lesson-${slug}">${e(content.lessons[slug].title)}</a>`).join(' · ')}</p>`:''}</header>${lesson.sections.map((s,i)=>renderScene(s,i,lesson,scenes[i])).join('')}${renderQuiz(lesson)}<section class="lesson-takeaway"><p class="eyebrow">기억할 한 가지</p><h2>${e(lesson.takeaway)}</h2><p>아래로 이어서 다음 개념을 만나세요.</p><div class="source-links">${lesson.sourceUrls.map((url,i)=>`<a href="${e(url)}">Python 공식 자료 ${i+1} ↗</a>`).join('')}</div></section></article>`;
}
function catalog(content) {
 return `<section class="catalog" id="courses"><p class="eyebrow">전체 학습 지도</p><h2>44개의 문제.<br>하나로 이어지는 이해.</h2>${content.curriculum.courses.map((c,i)=>`<div class="course"><span class="course-index">${n(i+1)}</span><div><h3>${e(c.title)}</h3><p>${e(c.question)}</p><ol>${c.lessons.map(slug=>`<li><a href="#lesson-${slug}"><span>${n(content.order.indexOf(slug)+1)}</span>${e(content.lessons[slug].title)}<i>↗</i></a></li>`).join('')}</ol></div></div>`).join('')}</section>`;
}
export function renderIndex(content) {
 return frame('스크롤하면, 코드가 보인다','스크롤만으로 코드와 상태 변화를 함께 살펴보는 Python 학습 여정.',`<main id="main">${hero()}<p class="motion-fallback" data-motion-fallback>스크롤 연출이 꺼져 있습니다. 모든 설명과 예제는 아래에서 읽을 수 있습니다.</p>${content.order.map(slug=>article(content.lessons[slug],content)).join('')}${catalog(content)}</main>`);
}
export function renderLesson(lesson,content) {
 const i=content.order.indexOf(lesson.slug),next=content.lessons[content.order[i+1]],previous=content.lessons[content.order[i-1]];
 return frame(lesson.title,lesson.goal,`<main id="main"><p class="motion-fallback" data-motion-fallback>스크롤 연출이 꺼져 있습니다. 모든 설명과 예제는 아래에서 읽을 수 있습니다.</p>${article(lesson,content,'../',true)}<nav class="lesson-navigation">${previous?`<a href="${previous.slug}.html">이전 · ${e(previous.title)}</a>`:''}${next?`<a href="../index.html#lesson-${next.slug}">이어서 · ${e(next.title)} →</a>`:''}<a href="../index.html#courses">전체 목차 보기</a></nav></main>`,'../');
}
